[tool.poetry]
name = "unreasonable-llama"
version = "0.1.0"
description = "Yet another Python API for llama.cpp server"
authors = ["SteelPh0enix <wojciech_olech@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
