[project]
name = "unreasonable-llama"
version = "0.5.0"
description = "HTTP API bindings for llama.cpp built-in example server"
authors = [{ name = "SteelPh0enix", email = "wojciech_olech@hotmail.com"}]
readme = "README.md"
license = "MIT"
requires-python = ">= 3.10"
dependencies = [
    "dataclasses-json>=0.6.7",
    "httpx>=0.28.1",
]

[tool.ruff]
line-length = 120

[tool.mypy]
strict = true
show_error_context = true
show_column_numbers = true
show_error_code_links = true
pretty = true

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.1",
    "ruff-lsp>=0.0.62",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
