[tool.poetry]
name = "unreasonable-llama"
version = "0.2.5"
description = "HTTP API bindings for llama.cpp built-in server"
authors = ["SteelPh0enix <wojciech_olech@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/SteelPh0enix/unreasonable-llama/"
keywords = ["llama.cpp", "llama", "llm", "api", "bindings"]

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
numpy = "^2.0.1"
sentencepiece = "^0.2.0"
pyyaml = "^6.0.2"
ruff = "^0.5.5"
ruff-lsp = "^0.0.54"
mypy = "^1.11.0"

[tool.ruff]
line-length = 120

[tool.mypy]
disable_error_code = ["type-arg", "valid-type"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
