[project]
name = "unreasonable-llama"
authors = [{ name = "SteelPh0enix", email = "<wojciech_olech@hotmail.com>" }]
version = "0.5.0"
description = "HTTP API bindings for llama.cpp built-in example server"
keywords = ["llama.cpp", "llama", "llm", "api", "bindings", "stateless"]
license.file = "LICENSE"
readme.file = "README.md"
requires-python = ">=3.12"
urls.repository = "https://github.com/SteelPh0enix/unreasonable-llama"

dependencies = ["httpx>=0.28.1"]

[dependency-groups]
dev = ["mypy>=1.18.2", "ruff>=0.14.0", "ruff-lsp>=0.0.62"]

[tool.ruff]
line-length = 120

[tool.mypy]
strict = true
show_error_context = true
show_column_numbers = true
show_error_code_links = true
pretty = true
