name: Check code formatting and validity
run-name: Check the library's code formatting and validity with Ruff and mypy.
on: push

jobs:
  check-code:
    name: Check Python code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install project dependencies"
        run: uv sync
      - name: "Check code formatting"
        run: uv run ruff format --diff ./unreasonable_llama/__init__.py
      - name: "Check code with ruff"
        run: uv run ruff check --no-fix ./unreasonable_llama/__init__.py
      - name: "Check code with mypy"
        run: uv run mypy ./unreasonable_llama/__init__.py
